# Generated by Django 3.2.5 on 2021-07-26 17:51

from django.db import migrations, models
import server.authentication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=server.authentication.models.generate_numeric_token, max_length=6)),
                ('type', models.CharField(choices=[('AUTH', 'Auth'), ('VERIFY', 'Verify')], max_length=20)),
                ('to_alias', models.CharField(blank=True, max_length=20, null=True)),
                ('to_alias_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
