# Generated by Django 3.2.5 on 2021-07-29 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.authentication.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_callbacktoken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbacktoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tokens', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='callbacktoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='DIRECCIÓN IP DE LA PETICIÓN'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='CREADO'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(default=server.authentication.utils.generate_numeric_token, max_length=6, verbose_name='CÓDIGO ENVIADO'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='to_alias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIPO ALIAS'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='to_alias_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PARA ALIAS TIPO'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='type',
            field=models.CharField(choices=[('AUTH', 'Autenticación'), ('VERIFY', 'Verificación'), ('PASSWORD_RESET', 'Reestablecer contraseña')], max_length=20, verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUARIO'),
        ),
    ]
