# Generated by Django 3.2.5 on 2021-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_callbacktoken_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='DISPOSITIVO DE PETICIÓN'),
        ),
    ]
