# Generated by Django 3.2.5 on 2021-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_callbacktoken_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='type',
            field=models.CharField(choices=[('AUTH', 'Autenticación'), ('VERIFY', 'Verificación'), ('PASSWORD_RESET', 'Reestablecer contraseña')], max_length=30, verbose_name='TIPO'),
        ),
    ]
