# Generated by Django 3.2.5 on 2021-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_callbacktoken_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='to_alias',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TIPO ALIAS'),
        ),
        migrations.AlterField(
            model_name='callbacktoken',
            name='to_alias_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PARA ALIAS TIPO'),
        ),
    ]
