# Generated by Django 3.2.5 on 2021-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_communicationeventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_html_template',
            field=models.TextField(blank=True, help_text='HTML template', null=True, verbose_name='Email Body HTML Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_body_template',
            field=models.TextField(blank=True, null=True, verbose_name='Email Body Template'),
        ),
        migrations.AddField(
            model_name='communicationeventtype',
            name='email_subject_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template'),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='category',
            field=models.CharField(choices=[('User related', 'USER_RELATED'), ('Driver related', 'DRIVER_RELATED'), ('Supervisor related', 'SUPERVISOR_RELATED')], max_length=50),
        ),
    ]
