# Generated by Django 3.2.5 on 2021-07-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20210715_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationeventtype',
            old_name='name',
            new_name='code',
        ),
    ]
