# Generated by Django 3.2.5 on 2021-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_rename_name_communicationeventtype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
