# Generated by Django 3.2.5 on 2021-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='rol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
