# Generated by Django 3.2.5 on 2021-07-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
