# Generated by Django 3.2.5 on 2021-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documenttype_documenttyperol'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='rol',
            field=models.ManyToManyField(through='users.DocumentTypeRol', to='users.Rol'),
        ),
    ]
