# Generated by Django 3.2.5 on 2021-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210713_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
