# Generated by Django 3.2.5 on 2021-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdocumenttyperol'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='document_type_rol_id',
            field=models.ManyToManyField(through='users.UserDocumentTypeRol', to='users.DocumentTypeRol'),
        ),
    ]
