# Generated by Django 3.2.5 on 2021-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_baseuser_document_type_rol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
