# Generated by Django 3.2.5 on 2021-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210720_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
