# Generated by Django 3.2.5 on 2021-07-22 16:25

from django.db import migrations, models
import server.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=server.users.utils.user_directory_path, verbose_name='Avatar'),
        ),
    ]
