# Generated by Django 3.2.5 on 2021-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacktoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='callbacktoken',
            name='to_alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callbacktoken',
            name='to_alias_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
