"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from .cors import *
from .sessions import *
from .env_reader import env
from .sms import *
from .users import *
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8zq79wpn50noa5#_=tram#w_ecnzt$%+$^&rzo5b2^4pr3nch0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition


LOCAL_APPS = [
    "server.common.apps.CommonConfig",
    "server.api.apps.ApiConfig",
    "server.users.apps.BaseUserConfig",
    "server.authentication.apps.AuthenticationConfig",
    "server.communication.apps.CommunicationConfig",
    "server.payments.apps.Paymentsconfig",

]

DEPENDENCIES_APPS = [
    "rest_framework",
    "corsheaders",
]

INSTALLED_APPS = [
    "django.contrib.sites",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    *LOCAL_APPS,
    *DEPENDENCIES_APPS
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Agregar middlewares de los cors para permitir el
    # acceso de fuentes externas.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DATABASE_NAME', default=''),
        'USER': 'postgres',
        'PASSWORD': env('DATABASE_PASSWORD', default=''),
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS': True
    }
}


# Configuración sobre los cors
# Permitir conecciones de fuentes externs.
CORS_ORIGIN_ALLOW_ALL = True

# Uso del modelo usuario de la base del framework.
# Personalizar modelo usuario.
AUTH_USER_MODEL = "users.BaseUser"

SITE_ID = 1

# Registro de emails en la base de datos.
# Si está desactivao, omite el respaldo.
SAVE_SENT_EMAILS_TO_DB = True

# Duración de dias del token generado de
# reestablecimiento de contraseñas.
# 1 días en segundos.
PASSWORD_RESET_TIMEOUT = 84.600

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Carpeta destinada a almacenar los archivos estáticos.
MEDIA_ROOT = os.path.join(os.getcwd(), 'media')


# Configuración de servidor de correos
# Esto afecta al envío de emails.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Configuración de credenciales de envío mensajes de texto.
SMS_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
SMS_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
SMS_TWILIO_NUMBER = env('TWILIO_NUMBER', default='')

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SITE_URL = 'http://localhost:3000/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Confguraciones personalizadas de rest framework
# El despachador de errores es personalizado.
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'server.api.errors.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': []
}
